swagger: "2.0"
info:
  title: YakoAPI
  description: An API to interact with YakoMaster
  version: 1.0.0
host: www
schemes:
  - https
  - http
paths:
  /alive:
    get:
      operationId: alive
      description: Checks YakoMaster availability
      responses:
        '200':
          description: YakoMaster is alive
        default:
          description: YakoMaster is down