openapi: 3.0.0
info:
  title: YakoAPI
  description: An API to interact with YakoMaster and the Yako platform
  version: 1.0.0
  contact:
    name: Jiahui Chen
    email: Jiahui1@hotmail.es
    url: https://github.com/JiahuiChen99/Yako
externalDocs:
  description: Find out how to run the Yako plaftorm
  url: 'https://github.com/JiahuiChen99/Yako#yako'
tags:
  - name: YakoMaster
    description: All resources to interact with YakoMaster
  - name: cpu_model
    x-displayName: The CPU Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/CPU" />
x-tagGroups:
  - name: General
    tags:
      - YakoMaster
  - name: Models
    tags:
      - cpu_model
      - gpu_model
      - sysinfo_model
      - memory_model
paths:
  /alive:
    get:
      operationId: alive
      description: Checks YakoMaster availability
      responses:
        '200':
          description: YakoMaster is alive
        default:
          description: YakoMaster is down
  /deploy:
    post:
      operationId: deploy
      description: Uploads the application, finds the most suitable node according to the specsheet and deploys in
      responses:
        '200':
          description: Returns top 3 best nodes with its brownie points.
          schema:
            type: array
            items:
              $ref: '#/definitions/YakoAgent'
        '400':
          description: Bad request, some requests params mighht be missing